Error in file.remove(log) : invalid first filename 
Traceback: 
1: file.remove(log) 

